import { FormEvent, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, ClipboardList, Package, Search, Warehouse } from "lucide-react";
import { Link } from "react-router-dom";
import PageLayout from "@/components/PageLayout";
import { useAuth } from "@/context/AuthContext";
import { accessToken, apiBaseUrl } from "@/lib/azure";
import { toast } from "@/hooks/use-toast";

type InventoryItem={id:string;sku:string;name:string;item_type:"product"|"component";unit:string;current_stock:number;minimum_stock:number;low_stock:boolean};
type Movement={id:number;movement_type:"purchase"|"sale"|"damage"|"adjustment";quantity:number;order_id?:string;invoice_number?:string;notes?:string;created_by?:string;created_at:string;sku:string;name:string;unit:string};
type InventoryResponse={items:InventoryItem[];movements:Movement[];stats:{item_count:number;low_stock_count:number;negative_stock_count:number}};
const movementLabel={purchase:"Entrada / compra",sale:"Salida por venta",damage:"Baja por daño",adjustment:"Ajuste"};

const AdminInventario=()=>{
  const {account,ready,login}=useAuth();
  const queryClient=useQueryClient();
  const [search,setSearch]=useState("");
  const [sku,setSku]=useState("");
  const [type,setType]=useState<"purchase"|"damage">("purchase");
  const [quantity,setQuantity]=useState("");
  const [notes,setNotes]=useState("");
  const [saving,setSaving]=useState(false);
  const inventory=useQuery({queryKey:["inventory"],enabled:Boolean(account),retry:false,queryFn:async()=>{const token=await accessToken(account!);const response=await fetch(`${apiBaseUrl}/inventory`,{headers:{"X-Golden-Bloom-Authorization":`Bearer ${token}`}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||"No se pudo cargar el inventario.");return body as InventoryResponse;}});
  const filtered=useMemo(()=>{const value=search.trim().toLowerCase();return inventory.data?.items.filter(item=>!value||item.name.toLowerCase().includes(value)||item.sku.toLowerCase().includes(value))||[];},[inventory.data,search]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!account)return;setSaving(true);try{const token=await accessToken(account);const response=await fetch(`${apiBaseUrl}/inventory-movements`,{method:"POST",headers:{"Content-Type":"application/json","X-Golden-Bloom-Authorization":`Bearer ${token}`},body:JSON.stringify({sku,type,quantity:Number(quantity),notes})});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||"No se pudo guardar el movimiento.");toast({title:type==="purchase"?"Entrada registrada":"Baja registrada",description:`Existencia actual: ${body.currentStock}`});setQuantity("");setNotes("");await queryClient.invalidateQueries({queryKey:["inventory"]});}catch(error){toast({title:"No se pudo actualizar el inventario",description:error instanceof Error?error.message:undefined,variant:"destructive"});}finally{setSaving(false);}};
  const stats=inventory.data?.stats;
  return <PageLayout><main className="container pt-32 pb-24 min-h-[70vh]">
    <header className="mb-9 flex flex-col md:flex-row md:items-end justify-between gap-5"><div><p className="text-xs tracking-[.35em] uppercase text-primary">Administración</p><h1 className="font-serif text-5xl mt-2">Inventario</h1><p className="text-muted-foreground mt-3">Controla entradas, ventas y pérdidas por daño.</p></div><nav className="flex flex-wrap gap-3"><Link to="/admin/pedidos" className="inline-flex items-center gap-2 border border-border px-5 py-3 text-xs uppercase tracking-wider"><ClipboardList size={16}/> Ver pedidos</Link><Link to="/admin/opciones-ramo" className="inline-flex items-center gap-2 border border-border px-5 py-3 text-xs uppercase tracking-wider">Opciones del ramo</Link></nav></header>
    {!ready?<p>Cargando…</p>:!account?<button onClick={()=>login()} className="bg-primary text-primary-foreground px-8 py-4 uppercase text-xs tracking-wider">Ingresar como administrador</button>:inventory.isError?<p className="border border-destructive/30 p-5">{inventory.error.message}</p>:<>
      {stats&&<section className="grid sm:grid-cols-3 gap-3 mb-7">{[["Artículos",stats.item_count,Warehouse],["Existencia baja",stats.low_stock_count,AlertTriangle],["Existencia negativa",stats.negative_stock_count,Package]].map(([label,value,Icon])=><div key={String(label)} className="bg-card border border-border p-5 flex items-center gap-3"><Icon className="text-primary" size={21}/><div><p className="font-serif text-3xl">{Number(value)}</p><p className="text-xs uppercase tracking-wider text-muted-foreground">{String(label)}</p></div></div>)}</section>}
      <section className="grid lg:grid-cols-[minmax(0,1fr)_360px] gap-7 items-start">
        <div><label className="relative block mb-4"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto o SKU…" className="w-full bg-card border border-border py-3 pl-10 pr-3 text-sm"/></label><div className="bg-card border border-border divide-y divide-border">{inventory.isLoading?<p className="p-8 text-center text-muted-foreground">Cargando inventario…</p>:filtered.map(item=><article key={item.id} className="p-4 flex items-center justify-between gap-4"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.sku} · {item.item_type==="component"?"Componente floral":"Producto"}</p></div><div className="text-right"><p className={`font-serif text-2xl ${item.low_stock?"text-destructive":""}`}>{Number(item.current_stock).toLocaleString("es-CR")} <span className="font-sans text-xs">{item.unit}</span></p>{item.low_stock&&<p className="text-[10px] uppercase tracking-wider text-destructive">Existencia baja</p>}</div></article>)}</div></div>
        <form onSubmit={submit} className="bg-card border border-border p-6 lg:sticky lg:top-28"><p className="text-xs tracking-[.3em] uppercase text-primary">Movimiento manual</p><h2 className="font-serif text-3xl mt-2">Actualizar existencia</h2><div className="grid grid-cols-2 gap-2 mt-6"><button type="button" onClick={()=>setType("purchase")} className={`p-3 text-xs uppercase tracking-wider border ${type==="purchase"?"bg-secondary text-secondary-foreground":"border-border"}`}><ArrowDownToLine size={16} className="mx-auto mb-1"/>Entrada</button><button type="button" onClick={()=>setType("damage")} className={`p-3 text-xs uppercase tracking-wider border ${type==="damage"?"bg-destructive text-destructive-foreground":"border-border"}`}><ArrowUpFromLine size={16} className="mx-auto mb-1"/>Daño</button></div><select required value={sku} onChange={e=>setSku(e.target.value)} className="w-full border border-border bg-background p-3 text-sm mt-5"><option value="">Selecciona un producto</option>{inventory.data?.items.map(item=><option key={item.id} value={item.sku}>{item.name} ({item.sku})</option>)}</select><input required type="number" min="0.01" step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Cantidad" className="w-full border border-border bg-background p-3 text-sm mt-3"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={400} placeholder={type==="damage"?"Motivo: marchita, quebrada, vencida…":"Proveedor, factura o detalle de compra"} className="w-full border border-border bg-background p-3 text-sm mt-3 min-h-24"/><button disabled={saving} className="w-full bg-primary text-primary-foreground p-4 text-xs uppercase tracking-[.2em] mt-4 disabled:opacity-50">{saving?"Guardando…":type==="purchase"?"Registrar entrada":"Sacar por daño"}</button></form>
      </section>
      <section className="mt-12"><h2 className="font-serif text-3xl mb-5">Movimientos recientes</h2><div className="bg-card border border-border divide-y divide-border">{inventory.data?.movements.map(m=><article key={m.id} className="p-4 grid md:grid-cols-[1fr_auto_auto] gap-3"><div><p className="font-medium">{m.name}</p><p className="text-xs text-muted-foreground">{m.sku}{m.notes?` · ${m.notes}`:""}</p></div><div className="md:text-right"><p className={Number(m.quantity)<0?"text-destructive":"text-primary"}>{Number(m.quantity)>0?"+":""}{Number(m.quantity).toLocaleString("es-CR")} {m.unit}</p><p className="text-xs text-muted-foreground">{movementLabel[m.movement_type]}</p></div><div className="md:text-right text-xs text-muted-foreground"><p>{new Date(m.created_at).toLocaleString("es-CR")}</p>{m.invoice_number&&<Link to="/admin/pedidos" className="text-primary">{m.invoice_number}</Link>}</div></article>)}</div></section>
    </>}
  </main></PageLayout>;
};

export default AdminInventario;
